spring.application.name=mail-service
server.port=8100
spring.config.import=optional:configserver:http://localhost:8888
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# Mail config default
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyentuanwd.ou@gmail.com
spring.mail.password=wpaoojadpuhsikxw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Environment dynamic
spring.profiles.active=development
spring.cloud.config.profile=development

#Grpc
spring.grpc.server.port=9090