spring.datasource.url=jdbc:mysql://localhost:3306/hiimtuan?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
security.jwt.expiration-time=7200000
security.jwt.refresh-expiration-time=36000000
security.jwt.change-password-expiration-time=300000