spring.application.name=common-service

security.jwt.expiration-time=604800000
security.jwt.refresh-expiration-time=2592000000
security.jwt.password-reset-expiration-time=1800000
security.jwt.secret-key=319f0adafdff4b4b62fa1574ae3e85d7f9b7fb171eecc0375f309f18a43fa09a